# Generated by Django 3.2.5 on 2021-08-20 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=54, unique=True, validators=[django.core.validators.RegexValidator(message='Only use 0-9, a-Z-_', regex='[0-9a-zA-Z-_]')]),
        ),
    ]
