# Generated by Django 3.2.5 on 2021-08-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('new', 'New'), ('in_work', 'In_work'), ('close', 'Close'), ('error', 'Error')], default='new', max_length=80),
        ),
    ]
