# Generated by Django 3.2.5 on 2021-08-17 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_alter_comments_text_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.ticket'),
        ),
    ]
