# Generated by Django 3.2.5 on 2021-09-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_alter_ticket_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='text',
            field=models.TextField(),
        ),
    ]
